ddc:
  boot-node: 'https://node-0.ddc.dev.cere.network'
  pub-key-hex: '0x16047c8f17b13b15021a1c2be99259fb08dda9bf517746795c6fb5fb3f461178'
  sec-key-hex: '0x3c18b7b6e1fe67af056e77870c65a019c65a7ed7052d550fcc191ca54d16ca9116047c8f17b13b15021a1c2be99259fb08dda9bf517746795c6fb5fb3f461178'
network:
  chain-id: 80001
  contract-address: '0x509Dfd7c670AC89246723EFe0f80f433BfbB6E5c'
  first-block-number: 15960010
  covalent-api-key: 'ckey_103992e94cd94393beb35d1456d'
  poll-interval: 'PT30S'
  event-topics:
    JointAccountShareCreated: '0x006fb9851f1fd2fbc9fa36680d17e1254999a38e5f3c76c3a1ecc126a464601b'
quarkus:
  datasource:
    db-kind: 'postgresql'
    username: 'pg'
    password: 'pwd'
    reactive:
      url: 'postgresql://localhost:5432/davinci'
  flyway:
    migrate-at-start: false
  log:
    console:
      enable: true
      level: 'INFO'
      json: false
  # Build section
  container-image:
    build: true
    push: false
    group: 'nft.davinci'
    name: 'davinci-sc-event-listener'
    tag: 'dev'

"%prod":
  quarkus:
    log:
      console:
        json: true
