covalent/mp-rest/url: 'https://api.covalenthq.com'
covalent/mp-rest/connectTimeout: 5000
covalent/mp-rest/readTimeout: 30000
ddc:
  enabled: false
  boot-nodes:
    - 'http://localhost:8888'
  pub-key-hex: '0xcafebabe'
  sec-key-hex: '0xcafebabe'
cms:
  enabled: false
  base-url: 'http://localhost:8888'
  login: 'api-user'
  password: 'api-password'
  routes:
    nft: 'creator-nfts'
    nft-cid: 'creator-nft-cids'
    nft-royalty: 'creator-nft-roaylties'
    make-offer: 'creator-make-offers'
    take-offer: 'creator-take-offers'
    auction: 'creator-auctions'
    auction-bid: 'creator-auction-bids'
    wallet: 'creator-wallet-nfts'
    exchange-rate: 'creator-exchange-rate'
    joint-account: 'creator-joint-accounts'
contracts:
  freeport:
    address: '0xd1EdBAC660307c5B6d22E678FB5e22668C70Ad96'
    first-block-number: 20997893
  fiat-gateway:
    address: '0x1f8eC932B6ec39A0326b74E9648A158F88B24082'
    first-block-number: 20998037
  auction:
    address: '0xd7cd23C84F9109F57f13eF28319e8787628DD7ad'
    first-block-number: 21074782
  nft-attachment:
    address: '0x270693f873287a39172856Ad8cfbCd79b040b287'
    first-block-number: 21202148
network:
  chain-id: 80001
  covalent-api-key: 'ckey_103992e94cd94393beb35d1456d'
  poll-interval: '1S'
quarkus:
  cache:
    caffeine:
      covalent:
        maximum-size: 2000
        expire-after-write: 1800S
  datasource:
    db-kind: 'postgresql'
  flyway:
    baseline-on-migrate: true
    migrate-at-start: true
    validate-on-migrate: true
    out-of-order: false
  hibernate-orm:
    log:
      sql: true
  log:
    console:
      enable: true
      level: 'INFO'
      json: false
  # Build section
  container-image:
    build: true
    push: false
    group: 'nft.freeport'
    name: 'freeport-sc-event-listener'
    tag: 'dev'

"%test":
  contracts:
    test-processor:
      address: '0x02'
      first-block-number: 0

"%prod":
  ddc:
    enabled: true
  quarkus:
    hibernate-orm:
      log:
        sql: false
    log:
      console:
        json: true
